Numpy is a python libabry that allows us to to store multi dimensions data such as matrix (or 1 dimension such as array). It also contains all the complex computational calculations. 

import numpy , * means import everything in the numpy package

In [2]:
from numpy import *
import numpy as np 

define the arrays

In [2]:
a = np.array([1.3,2.4,3.443,4.345])
b = np.array([2,6,-3,8])

find index in arrays

In [33]:
a[0], a[3]

(1.3, 4.345)

In [34]:
b[3], b[0]

(8, 2)

In [35]:
b[[1,2,3]] #faster way to ask for index content, list in a list

array([ 6, -3,  8])

#find the type of array

In [37]:
a.dtype

dtype('float64')

In [36]:
b.dtype 

dtype('int64')

In [39]:
c.dtype

dtype('<U2')

Dimensions and Shape

In [50]:
d = np.array([
    [1,2,3],
    [4,5,6]
])

In [51]:
d.shape

(2, 3)

In [52]:
d.size

6

In [53]:
d.ndim

2

add rows in an array

In [5]:
d[1]= [100,1,2]

In [6]:
print(d)

[[  1   2   3]
 [100   1   2]]


some built in functions 

In [7]:
janice = np.array([40,41,39])

In [8]:
janice.sum()

120

In [9]:
janice.mean()

40.0

In [10]:
janice.std() #standard deviation

0.816496580927726

In [11]:
janice.var()

0.6666666666666666

In [28]:
wei = np.array([
                [1,2,3],
                [3,4,1],
                [6,4,8],]
            )

vertical sum 

In [31]:
wei.sum(axis=0)

array([10, 10, 12])

horizontal sum 

In [54]:
wei.sum(axis=1)

array([ 6,  8, 18])

broadcasting and vectorizing arrays 

In [5]:
a = np.arange(4)

In [6]:
a

array([0, 1, 2, 3])

adding 10 to each element in the array

In [7]:
a + 10

array([10, 11, 12, 13])

In [8]:
a * 10

array([ 0, 10, 20, 30])

In [12]:
a += 100

Boolean Arrays

In [67]:
c = np.arange(4)

In [68]:
c

array([0, 1, 2, 3])

In [69]:
c.dtype

dtype('int64')

Ways to find index in arrays

In [70]:
c[0],c[-1] #first way

(0, 3)

In [25]:
c[[0,-1]] # second way

array([0, 3])

In [71]:
c[[True,False,False,True]] #third way, true false need to be the same size with the array

array([0, 3])

In [72]:
c >= 2 #check every element in the array whether it's bigger or equal to 2

array([False, False,  True,  True])

In [73]:
c[c >= 2]

array([2, 3])

In [74]:
c[c > c.mean()]

array([2, 3])

In [75]:
c[~(c > c.mean())]

array([0, 1])

random generating arrays 

In [1]:
c = np.random.randint(100,size = (3,3))

NameError: name 'np' is not defined

In [81]:
c.dtype

dtype('int64')

In [82]:
c

array([[72, 53,  9],
       [57, 37, 52],
       [23, 91, 37]])

In [86]:
c[np.array([
    [True,False,True],
    [False,True,False], 
   [True,False,True]
   ])]

array([72,  9, 37, 23, 37])

In [84]:
c [ c > 10]

array([72, 53, 57, 37, 52, 23, 91, 37])

In [89]:
c.std()

23.416254774287047

In [88]:
c [ c > c.std()]

array([72, 53, 57, 37, 52, 91, 37])

In [101]:
carbohydrates = np.array([[2.8,2.5,2.8,2.3,2.6,2.1],
                         [3.6,3.1,2.9,3.7,3.2,3.3]])

In [104]:
mean = np.mean(carbohydrates[1])

In [105]:
mean

3.3000000000000003

transpose 

In [3]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

In [4]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

Speed differernce between numpy and python 

In [5]:
l = list(range(1000)) # python

In [7]:
ll = np.arange(1000) #numpy

In [20]:
%time sum([x**2 for x in l]) #python way 

CPU times: user 669 µs, sys: 14 µs, total: 683 µs
Wall time: 673 µs


332833500

In [25]:
%time np.sum(ll**2) #numpy way 

CPU times: user 135 µs, sys: 18 µs, total: 153 µs
Wall time: 148 µs


332833500